version: '3.7'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    # restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - wa2_net
    image: ${DHUB_USER}/ch05_flask_dev:${IMG_VER}
    container_name: ch05_flask_dev-container
    stop_signal: SIGINT
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    # restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - wa2_net
    image: ${DHUB_USER}/ch05_nginx_dev:${IMG_VER}
    container_name: ch05_nginx_dev-container
    volumes:
      - ./web/html:/usr/share/nginx/html

networks:
  wa2_net:
    driver: bridge
